### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by kenjikawamata3** [kenjikawamata3/selfNavi#1]
##概要
・Laravel + Vue.js でSPA構築する
・エラーなくlaravel top画面が表示され、実装の下準備ができることを目的とする

##Todo
- [x] show laravel top page
- [x] install laravel/ui 
- [x] install laravel/ui vue 
- [x] install npm
- [ ] install vue router
参考：https://qiita.com/minato-naka/items/2d2def4d66ec88dc3ca2

**Comment by kenjikawamata3** [comment]
vue router は必要に応じて別途インストールしてください。
下準備ができたためこの課題をクローズします。
